// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Mahdi Peydai",
            "email": "mahdipeydai@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/health": {
            "get": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.BaseHTTPResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helpers.BaseHTTPResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "result": {},
                "result_code": {
                    "$ref": "#/definitions/helpers.ResultCode"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "helpers.ResultCode": {
            "type": "integer",
            "enum": [
                0,
                50001
            ],
            "x-enum-varnames": [
                "Success",
                "CustomRecovery"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "TaskManager - Go",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
