Server:
  internalPort: 5000
  ExternalPort: 8080
  allowOrigins: "*"
  rateLimit: 1
Postgres:
  host: localhost
  port: 6432
  username: postgres
  password:
  dbName: car_sale_db
  sslMode: disable
  maxIdleConnections: 5
  maxOpenConnections: 10
  connectionMaxLifetime: 5
redis:
  host: localhost
  port: 5379
  password:
  database: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500
logger:
  appName: graph_taskmanager
  filePath: ../logs/
  level: debug
  loggerName: zap
admin:
  password: "1qaz!QAZ"
jwt:
  secret: "changeme"
  refreshSecret: "changeme"
  accessTokenExpireTime: 60
  refreshTokenExpireTime: 60
password:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true